config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'kiosk'

urlpatterns = [
    path('', views.Main, name='main'),
    path('place/', views.Place, name='place'),
    path('face/', views.Face, name='face'),
    path('face/load/', views.Load, name='load'),
    path('menu/', views.Menu, name='menu'),
    path('menu1/', views.Menu1, name='menu1'),
    path('menu2/', views.Menu2, name='menu2'),
    path('menu3/', views.Menu3, name='menu3'),
    path('menu4/', views.Menu4, name='menu4'),
    # path('menu5/', views.Menu5, name='menu5'),
    path('menu/order/', views.Order, name='order'),
    path('kitchen/', views.Kitchen, name='kitchen'),
    path('favor/', views.Favorlist, name='favor'),

    path('menulist/', views.MenuList, name='menulist'),
    path('menulist/<int:food_id>/', views.food_detail, name='food_detail'),
    # path('menulist/add_menulist/', views.add_menulist, name='add_menulist'),
]

main/models.py
from django.db import models


# Create your models here.
class Customer(models.Model):
    order_num = models.BigAutoField(primary_key=True)
    date = models.DateTimeField(auto_now_add=True, null=False)
    gender = models.CharField(max_length=50, blank=True, null=True)
    age_group = models.CharField(max_length=255, blank=True, null=True)
    total_num = models.IntegerField(default=0, null=False)
    total_price = models.IntegerField(default=0, null=False)


class List(models.Model):
    food_num = models.BigAutoField(primary_key=True)
    food_name = models.CharField(max_length=200, null=False)
    price = models.IntegerField(default=0, null=False)
    food_explain = models.TextField(max_length=2000, blank=True, null=True)
    allergy = models.CharField(max_length=250, null=True, blank=True)
    category = models.CharField(max_length=250, null=False)
    image = models.ImageField(upload_to='static/menuimg/', blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.food_name)

    # def get_photo_url(self):
    #     if self.image and hasattr(self.image, 'url'):
    #         return self.image.url


class Bill(models.Model):
    order_num = models.ForeignKey(Customer, on_delete=models.CASCADE)
    food_num = models.ForeignKey(List, on_delete=models.CASCADE)


class Favor(models.Model):
    favor_num = models.BigAutoField(primary_key=True)
    food_num = models.ForeignKey(List, on_delete=models.CASCADE)
    under30m = models.IntegerField(default=0, null=True)
    under50m = models.IntegerField(default=0, null=True)
    upper50m = models.IntegerField(default=0, null=True)
    under30f = models.IntegerField(default=0, null=True)
    under50f = models.IntegerField(default=0, null=True)
    upper50f = models.IntegerField(default=0, null=True)
    total_order = models.IntegerField(default=0, null=True)


from django.db import models

# Create your models here.

main/views.py
# from django.views.generic.base import TemplateView
#
# class Main(TemplateView):
#     template_name = 'main.html'

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import List
from django.core.paginator import Paginator
from django.db.models import Q
# from .forms import Menuform
from django.http import HttpResponse
from django.views.decorators.clickjacking import xframe_options_sameorigin

def Main(request):
    return render(request, 'main.html')


def Place(request):
    return render(request, 'place.html')


def Face(request):
    return render(request, 'face.html')


def Load(request):
    return render(request, 'load.html')

@xframe_options_sameorigin
def Menu(request):
    return render(request, 'menu.html')

@xframe_options_sameorigin
def Menu1(request):
    q = List.objects.values_list('category', flat=True).distinct()
    page = request.GET.get('page', '1')  # 페이지
    coffee_category = List.objects.filter(category='커피')
    coffee_paginator = Paginator(coffee_category, 6)  # 페이지당 n개씩 보여주기
    coffee_page_obj = coffee_paginator.get_page(page)
    context = {
        'coffee_category':coffee_page_obj,
        'q':q,
        }
    return render(request, 'menu1.html', context)

@xframe_options_sameorigin
def Menu2(request):
    q = List.objects.values_list('category', flat=True).distinct()
    page = request.GET.get('page', '1')  # 페이지
    tea_category = List.objects.filter(category='차')
    tea_paginator = Paginator(tea_category, 6)  # 페이지당 n개씩 보여주기
    tea_page_obj = tea_paginator.get_page(page)
    context = {
        'tea_category':tea_page_obj,
        'q':q,
        }
    return render(request, 'menu2.html', context)

@xframe_options_sameorigin
def Menu3(request):
    q = List.objects.values_list('category', flat=True).distinct()
    page = request.GET.get('page', '1')  # 페이지
    beverage_category = List.objects.filter(category='음료')
    beverage_paginator = Paginator(beverage_category, 6)  # 페이지당 n개씩 보여주기
    beverage_page_obj = beverage_paginator.get_page(page)
    context = {
        'beverage_category':beverage_page_obj,
        'q':q,
        }
    return render(request, 'menu3.html', context)

@xframe_options_sameorigin
def Menu4(request):
    q = List.objects.values_list('category', flat=True).distinct()
    page = request.GET.get('page', '1')  # 페이지
    dessert_category = List.objects.filter(category='디저트')
    dessert_paginator = Paginator(dessert_category, 6)  # 페이지당 n개씩 보여주기
    dessert_page_obj = dessert_paginator.get_page(page)
    context = {
        'dessert_category':dessert_page_obj,
        'q':q,
        }
    return render(request, 'menu4.html', context)

def Order(request):
    return render(request, 'order.html')


def Kitchen(request):
    return render(request, 'kitchen.html')


def Favorlist(request):
    return render(request, 'favor.html')

# MenuList 관련 View ------------------------------

def MenuList(request):
    food_list = List.objects.order_by('food_num')
    context = {'food_list':food_list}
    return render(request, 'menulist.html', context)


def food_detail(request, food_id):
    food = get_object_or_404(List, pk=food_id)
    context = {'food': food}
    return render(request, 'food_detail.html', context)


def Category_test(request, word):
    food_category = List.objects.filter(category=word).values()
    return HttpResponse(food_category)

def test(request):
    q = List.objects.values_list('category', flat=True).distinct()
    q_dict = {
        'q':q,
    }

    return HttpResponse(q_dict)

templates/face.html
{% extends "base.html" %}
{% load static %}


{% comment %} {% block extrastyle %} {% static 'stylesheets/face.css' %} {% endblock %} {% endcomment %}
{% block title %} face {% endblock %}
    
{% block content %}
            <div id="main">
                <div class="text"><p>인공지능 <span style='color:green; font-size:3vw;'><b>미리내</b></span> 입니다! 
                    <br> 고객님의 <b>나이, 성별</b>에 맞춰 메뉴를 <span style='color:red'><b>인기순</b></span>으로 정렬해 드릴까요?</p></div>
                <div class="btn">
                    <a type="button" href="load/" class="btn btn-lg yes"><b>좋아요</b></a>
                    <a type="button" href="{% url 'kiosk:menu' %}" class="btn btn-lg no"><b>싫어요</b></a>
                </div>
            </div>
{% endblock %}

templates/favor.html
{% extends "base.html" %}
{% load static %}

{% block extrastyle %} {% static 'stylesheets/favor.css' %} {% endblock %}
{% block title %} favor.html {% endblock %}

{% block content %}
{% endblock %}

templates/kitchen.html
{% extends "base.html" %}
{% load static %}

{% block extrastyle %} {% static 'stylesheets/kitchen.css' %} {% endblock %}
{% block title %} kitchen.html {% endblock %}

{% block content %}
{% endblock %}

templates/load.html
{% extends "base.html" %}
{% load static %}


{% block extrastyle %} {% static 'stylesheets/load.css' %} {% endblock %}
{% block title %} load {% endblock %}
    
{% block content %}
    <div class="text"><p>인기순으로 메뉴 정렬 중...</p></div>

    <div class="loader">
    </div>

    <div class="container" style="display:none;">
      <meta http-equiv="refresh" content="3; url={% url 'kiosk:menu' %}">
    <div>

    <script>
      var loader = $("div.loader");
      var container = $("div.container");
      loader.css("display","none");
      container.css("display","block");
    </script>
{% endblock %}

templates/menu2.html
{% extends "base.html" %}
{% load static %}

{% block title %} menu {% endblock %}
{% comment %} {% block extrastyle %} {% static 'stylesheets/menu.css' %} {% endblock %} {% endcomment %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% block content %}

<body>
        <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu1' %}">커피</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'kiosk:menu2' %}">차</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu3' %}">음료</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu4' %}">디저트</a>
        </li>
    </ul>
    <div class="container">
            <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="차">
            {% if tea_category %}
            {% for tea in tea_category%}
                <div class="list-box">
                    <div class="card h-100" type="button" value='innerHTML' onclick="addRow('{{tea.food_name}}', '{{tea.price}}')">
                        {% if tea.image  %}
                        <!-- Product image-->
                            <img style="aspect-ratio: 4 / 3; object-fit: contain;" src="{{tea.image.url}}" alt="" >
                        {% else %}
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        {% endif %}
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{tea.food_name}}</h5>
                                <!-- Product price-->
                                <p class="fw-lighter">{{tea.price}} 원</p>
                            </div>
                        </div>
                        <!-- Product actions-->
                    </div>
                </div>
            {% endfor %}

            {% endif %}

                            <!-- 티 페이징처리 시작 -->
                <div class="paging">
                    <ul class="pagination justify-content-center">
                        <!-- 이전페이지 -->
                        {% if tea_category.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ tea_category.previous_page_number }}">이전</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                        </li>
                        {% endif %}
                        <!-- 페이지리스트 -->
                        {% for page_number in tea_category.paginator.page_range %}
                        {% if page_number == tea_category.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% endif %}
                        {% endfor %}
                        <!-- 다음페이지 -->
                        {% if tea_category.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ tea_category.next_page_number }}">다음</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                        </li>
                        {% endif %}
                    </ul>
                    <!-- 페이징처리 끝 -->
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %} 

templates/menu3.html
{% extends "base.html" %}
{% load static %}

{% block title %} menu {% endblock %}
{% comment %} {% block extrastyle %} {% static 'stylesheets/menu.css' %} {% endblock %} {% endcomment %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% block content %}

<body>
        <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu1' %}">커피</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu2' %}">차</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'kiosk:menu3' %}">음료</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu4' %}">디저트</a>
        </li>
    </ul>
    <div class="container">
            <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="음료">
            {% if beverage_category %}
            {% for beverage in beverage_category%}
                <div class="list-box">
                    <div class="card h-100" type="button" value='innerHTML' onclick="addRow('{{beverage.food_name}}', '{{beverage.price}}')">
                        {% if beverage.image  %}
                        <!-- Product image-->
                            <img style="aspect-ratio: 4 / 3; object-fit: contain;" src="{{beverage.image.url}}" alt="" >
                        {% else %}
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        {% endif %}
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{beverage.food_name}}</h5>
                                <!-- Product price-->
                                <p class="fw-lighter">{{beverage.price}} 원</p>
                            </div>
                        </div>
                        <!-- Product actions-->
                    </div>
                </div>
            {% endfor %}

            {% endif %}

                            <!-- 음료 페이징처리 시작 -->
                <div class="paging">
                    <ul class="pagination justify-content-center">
                        <!-- 이전페이지 -->
                        {% if beverage_category.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ beverage_category.previous_page_number }}">이전</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                        </li>
                        {% endif %}
                        <!-- 페이지리스트 -->
                        {% for page_number in beverage_category.paginator.page_range %}
                        {% if page_number == beverage_category.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% endif %}
                        {% endfor %}
                        <!-- 다음페이지 -->
                        {% if beverage_category.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ beverage_category.next_page_number }}">다음</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                        </li>
                        {% endif %}
                    </ul>
                    <!-- 페이징처리 끝 -->
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %} 

templates/menu4-1.html
{% extends "base.html" %}
{% load static %}

{% block title %} menu {% endblock %}


{% comment %} {% block extrastyle %} {% static 'stylesheets/menu.css' %} {% endblock %} {% endcomment %}

{% block content %}
    <header>
        <nav>
            <div class="container1">

                    <a class="logo">
                        <span class="symbol"><img src="{% static 'images/logo-w.png' %}" alt="" /></span>
                    </a>

                    <a href="{% url 'kiosk:place' %}" class="home">
                        <img src="{% static 'images/home.png' %}" alt="" />
                    </a>
            </div>
        </nav>
    </header>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <body>
        <!-- Nav tabs -->
      <ul class="nav nav-tabs nav-justified">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu1' %}">커피</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu2' %}">차</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu3' %}">음료</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'kiosk:menu4' %}">디저트</a>
          </li>
      </ul>

    <div class="container">
            <!-- Tab panes -->
      <div class="tab-content">
      <div class="tab-pane active" id="디저트">
        {% if dessert_category %}
        {% for dessert in dessert_category%}
        
        {% comment %} <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">  {% endcomment %}
                    <div class="list-box">
                        <div class="card h-100" type="button" value='innerHTML' onclick='setInnerHTML()'>
                            {% if dessert.image  %}
                            <!-- Product image-->
                                <img style="aspect-ratio: 4 / 3; object-fit: contain;" src="{{dessert.image.url}}" alt="" >
                            {% else %}
                                <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            {% endif %}
                            <!-- Product details-->
                            <div class="card-body p-4">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{dessert.food_name}}</h5>
                                    <!-- Product price-->
                                    <p class="fw-lighter">{{dessert.price}} 원</p>
                            </div>
                            <!-- Product actions-->
                        </div>
                    </div>                        
                {% comment %} </div>
            </div>
        </section> {% endcomment %}

        
        {% endfor %}

        {% endif %}
                      <!-- 디저트 페이징처리 시작 -->
                      <div class="paging">
                        <ul class="pagination justify-content-center">
                            <!-- 이전페이지 -->
                            {% if dessert_category.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ dessert_category.previous_page_number }}">이전</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                            </li>
                            {% endif %}
                            <!-- 페이지리스트 -->
                            {% for page_number in dessert_category.paginator.page_range %}
                            {% if page_number == dessert_category.number %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                            </li>
                            {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                            </li>
                            {% endif %}
                            {% endfor %}
                            <!-- 다음페이지 -->
                            {% if dessert_category.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ dessert_category.next_page_number }}">다음</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                            </li>
                            {% endif %}
                        </ul>
                        <!-- 페이징처리 끝 -->
                    </div>
      </div>
      </div>
    </div>
  </body>

<!--            {% comment %} <button type="button" class="btn btn-secondary btn-lg prev">이전</button>
            <button type="button" class="btn btn-secondary btn-lg next">다음</button> {% endcomment %}-->
    <div class="ah">
        <div id="record">
            <div id="wrap">
              <main>
                <button class="mic">
                  <img class="abc dictate" src="{% static 'images/mic_org.png' %}" />
                </button>
              </main>
                <div class="mic-text">
                  <b>마이크를 누르고 </br>주문하실 메뉴를 말씀해주세요</b>
                </div>
            </div>
            <div class="search">
              <div class="input-bar">
                <input
                  type="hidden"
                  placeholder="검색어를 입력하세요"
                  autocomplete="off"
                  id="search_kw"
                  class="form-control"
                  value=" ="{{kw|default_if_none:''}}"/>
                <form id="searchForm" method="get" action="{% url 'kiosk:menulist' %}"> <!-- 값 전송-->
                  <button class="submitbtn" type="submit" id="search">▶</button>
                  <input type="hidden" id="kw" name="kw" value="="{{kw|default_if_none:''}}">
              </div>
            </div>
        </div>

        <div id="history">
            <h4>주문내역</h4><hr>
            <div id='my_div'>
                  <span></span>
            </div>
            <!--<p>총 금액 : </p>-->
            <div class="payment">
<!--                <button class="btn btn-secondary btn-lg" type="button" disabled>전체 취소</button>-->
                <input class="btn btn-secondary btn-lg" type='button' value='전체 취소' onclick='refresh()' />
                <!--button class="btn btn-success btn-lg" type="button">주문 확인</button-->
                <input id="popup_open_btn" class="btn btn-success btn-lg" type="button" value='주문 확인' />
            </div>
        </div>



<!--        <div id="my_modal">
            <a class="modal_close_btn">닫기</a>
        </div>-->

        <div id="my_modal" class="pop_wrap" style="display:none;">
            <p class="dsc">주문 확인</p><hr>
            <div class="btns">
                <a type="button" class="btn btn-secondary btn-lg btn_close" >닫기</a>
                <a type="button" class="btn btn-success btn-lg pay-money">현금</a>
                <a type="button" class="btn btn-primary btn-lg pay-card">카드</a>
            </div>
        </div>
    </div>


        <!-- Footer-->
        <!--footer class="py-5 bg-dark"-->
<!--            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>-->
        <!-- Core theme -->
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="{% static 'js/10-11.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
{% endblock %} 

templates/menu4.html
{% extends "base.html" %}
{% load static %}

{% block title %} menu {% endblock %}
{% comment %} {% block extrastyle %} {% static 'stylesheets/menu.css' %} {% endblock %} {% endcomment %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% block content %}

<body>
        <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu1' %}">커피</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu2' %}">차</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kiosk:menu3' %}">음료</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'kiosk:menu4' %}">디저트</a>
        </li>
    </ul>
    <div class="container">
            <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="디저트">
            {% if dessert_category %}
            {% for dessert in dessert_category%}
                <div class="list-box">
                    <div class="card h-100" type="button" value='innerHTML' onclick="addRow('{{dessert.food_name}}', '{{dessert.price}}')">
                        {% if dessert.image  %}
                        <!-- Product image-->
                            <img style="aspect-ratio: 4 / 3; object-fit: contain;" src="{{dessert.image.url}}" alt="" >
                        {% else %}
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        {% endif %}
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{dessert.food_name}}</h5>
                                <!-- Product price-->
                                <p class="fw-lighter">{{dessert.price}} 원</p>
                            </div>
                        </div>
                        <!-- Product actions-->
                    </div>
                </div>
            {% endfor %}

            {% endif %}

                            <!-- 디저트 페이징처리 시작 -->
                <div class="paging">
                    <ul class="pagination justify-content-center">
                        <!-- 이전페이지 -->
                        {% if dessert_category.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ dessert_category.previous_page_number }}">이전</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                        </li>
                        {% endif %}
                        <!-- 페이지리스트 -->
                        {% for page_number in dessert_category.paginator.page_range %}
                        {% if page_number == dessert_category.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% endif %}
                        {% endfor %}
                        <!-- 다음페이지 -->
                        {% if dessert_category.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ dessert_category.next_page_number }}">다음</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                        </li>
                        {% endif %}
                    </ul>
                    <!-- 페이징처리 끝 -->
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %} 

templates/menulist.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/bootstrap.min.css' %}">

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
        </tr>
        </thead>
        <tbody>
        {% if food_list %}
        {% for food in food_list%}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'kiosk:food_detail' food.food_num %}">{{food.food_name}}</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">메뉴가 존재하지 않습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    {% comment %} <a href="{% url 'kiosk:add_menulist' %}" class="btn btn-primary">메뉴 추가하기</a> {% endcomment %}
</div>

templates/order.html
{% extends "base.html" %}
{% load static %}

{% block extrastyle %} {% static 'stylesheets/order.css' %} {% endblock %}
{% block title %} order.html {% endblock %}

{% block content %}
{% endblock %}